service: url-zip-s3
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  url:
    handler: handler.handler
    timeout: 30
    events:
      - http:
          path: /download
          method: post
  zipFileAndTriggerEmail:
    handler: core.handler
    timeout: 900
    memorySize: 1024

plugins:
  - serverless-offline